### PR TITLE
Added my part

### PR DESCRIPTION
**Pull request by xxHACKYHACKYXx**
Deleted all your lame stuff and uploaded mine

### CODE REVIEW

**Comment by thel3l** [comment]
""Lame stuff"". Considering that I'm the one with the 'Merge Pull Request' button, a little nicety would go a long way.

**Comment by lunaroyster** [comment]
Who's doing the JS?

**Comment by rithvikvibhu** [comment]
Who owns xxhackyhackyxx? i tried hijacking it but couldn't figure how to use lasersharks :/

**Comment by thel3l** [comment]
fakena.me

**Comment by thel3l** [comment]
@lunaroyster owns it. It was an account that he created to use on public computers.

**Comment by lunaroyster** [comment]
Did you remove it as a contributor?

**Comment by thel3l** [comment]
Obviously.

**Pull request merged**
