### PR TITLE
Made some vital changes, structured code mess.

### PR DESCRIPTION
**Pull request by thebongy**
List of changes made:
1. Wrapped Startup spash screen in a function. (line 26-40).
2.  Added Exit or quit keyword message (Line 46).
3.  main_control() function changes:
        --> While loop at beginning was completely unecessary, removed.
        --> Never use usr_input() except for debugging purposes, Instead use raw_input(). It converts inputed character buffer to a string, thus preventing program termination if unknown character is entered.
        --> Made if condition check the number input as a string and not as a integer, because of raw_input(). Added conditions for exit, no input, and invalid input.
        --> Finally, called main_control() on Line 80, thus structuring code, and increasing code readibility.
        --> Called program flow functions one by one in a  `if __name__ ==" __main__"` block to prevent execution of program as a module. This ensures program is executed by itself, and not as a dependency of another program.

### CODE REVIEW

**Comment by thel3l** [comment]
@thebongy Why are you using to python 2? Raw_input is deprecated. Use input instead.

**Comment by lunaroyster** [comment]
@thebongy Nice!!

**Comment by thel3l** [comment]
You're telling me to use raw_input? https://docs.python.org/3/whatsnew/3.0.html

**Comment by thebongy** [comment]
@thel3l oh sorry, wasn't aware you guys were sticking to Python 3, will revert that back.

**Comment by thebongy** [comment]
@thel3l how about this: Since you guys are already using the `sys` module, why not use `sys.version_info` and check the version with a one liner? Cause as I see it, this is the only line in the whole program with a portability problem between python versions, right?

**Comment by thebongy** [comment]
@thel3l  @lunaroyster  just have a look at that, is that fine?

**Comment by thebongy** [comment]
@thel3l  If you are doinng python 3 in the first place, then shouldn't `print` be a function?

**Comment by thel3l** [comment]
Perfect. Will merge.

**Comment by thebongy** [comment]
wait a minute

**Comment by thebongy** [comment]
there are more errors on some print statements, just found them....., correcting those

**Comment by thel3l** [comment]
..

**Comment by thebongy** [comment]
@thel3l  can you just test this with python 3 before merging? Thanks.

**Comment by thel3l** [comment]
Nice!

**Pull request merged**
